<?xml version="1.0" encoding="utf-8"?><Database Name="D:\ДОКУМЕНТЫ\GITHUB\WPFAPP_01\DB\PERSONALDB.MDF" Class="EmployesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=D:\ДОКУМЕНТЫ\GITHUB\WPFAPP_01\DB\PERSONALDB.MDF;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="SpamLib.Properties.Settings" SettingsPropertyName="D__ДОКУМЕНТЫ_GITHUB_WPFAPP_01_DB_PERSONALDB_MDFConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employes" Member="EmployesDB">
    <Type Name="EmployesDB">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Patronymic" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DeptID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PositionID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Salary" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>